version: '3.1'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: LAB
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: